all: compile

compile:
	gcc -o Debug/Plataforma GUI/Introduccion.c GUI/Animaciones.c Plataforma.c Orquestador.c Planificador.c -I/home/utnso/GITHUB/tp-2013-2c-the-grid/Commons-Library -L/home/utnso/GITHUB/tp-2013-2c-the-grid/Commons-Library/Debug -I/home/utnso/GITHUB/tp-2013-2c-the-grid/Biblioteca -L/home/utnso/GITHUB/tp-2013-2c-the-grid/Biblioteca/Debug -I/home/utnso/GITHUB/tp-2013-2c-the-grid/nivel-gui -L/home/utnso/GITHUB/tp-2013-2c-the-grid/nivel-gui/Debug -lCommons-Library -lBiblioteca -lnivel-gui -lpthread
