compile:
	gcc -o nivel nivel.c cargador.c gui.c -I/home/utnso/workspace/commons/ -L/home/utnso/workspace/commons/Debug -lcommons -I/home/utnso/workspace/so-nivel-gui-library/nivel-gui -L/home/utnso/workspace/so-nivel-gui-library/nivel-gui/Debug -lnivel-gui -lncurses



#nivel: nivel.c cargador.c  /home/utnso/workspace/commons/commons/config.c /home/utnso/workspace/commons/commons/collections/dictionary.c /home/utnso/workspace/commons/commons/string.c /home/utnso/workspace/commons/commons/collections/list.c
#	gcc  -o nivel nivel.c cargador.c  /home/utnso/workspace/commons/commons/config.c /home/utnso/workspace/commons/commons/collections/dictionary.c /home/utnso/workspace/commons/commons/string.c /home/utnso/workspace/commons/commons/collections/list.c -I/home/utnso/workspace/commons
	
