all: compile

compile:

#    gcc -o nivel nivel.c cargador.c gui.c enemigos.c -I/home/utnso/workspace/commons/ -L/home/utnso/workspace/commons/Debug -lcommons -I/home/utnso/workspace/so-nivel-gui-library/nivel-gui -L/home/utnso/workspace/so-nivel-gui-library/nivel-gui/Debug -lnivel-gui -lncurses -I/home/utnso/GitMario/tp-2013-2c-the-grid/Biblioteca/theGRID -L/home/utnso/GitMario/tp-2013-2c-the-grid/Biblioteca/theGRID/Debug -ltheGrid

#	gcc -o nivel nivel.c cargador.c  -I/home/utnso/workspace/commons/ -L/home/utnso/workspace/commons/Debug -lcommons 
#	gcc -o nivel nivel.c cargador.c gui.c enemigos.c conexiones.c -I/home/utnso/workspace/commons/ -L/home/utnso/workspace/commons/Debug -lcommons -I/home/utnso/workspace/so-nivel-gui-library/nivel-gui -L/home/utnso/workspace/so-nivel-gui-library/nivel-gui/Debug -lnivel-gui -lncurses -I/home/utnso/GitMario/tp-2013-2c-the-grid/Biblioteca/theGRID -L/home/utnso/GitMario/tp-2013-2c-the-grid/Biblioteca/theGRID/Debug -ltheGrid
	gcc -o nivel nivel.c cargador.c gui.c enemigos.c conexiones.c personajes.c interbloqueo.c -I/home/utnso/GITHUB/tp-2013-2c-the-grid/Commons-Library -L/home/utnso/GITHUB/tp-2013-2c-the-grid/Commons-Library/Debug -lCommons-Library -I/home/utnso/GITHUB/tp-2013-2c-the-grid/nivel-gui -L/home/utnso/GITHUB/tp-2013-2c-the-grid/nivel-gui/Debug -lnivel-gui -lncurses -I/home/utnso/GITHUB/tp-2013-2c-the-grid/Biblioteca -L/home/utnso/GITHUB/tp-2013-2c-the-grid/Biblioteca/Debug -lBiblioteca -lpthread -lm





