nivel: nivel.c cargador.c /home/utnso/workspace/commons/commons/config.c /home/utnso/workspace/commons/commons/collections/dictionary.c /home/utnso/workspace/commons/commons/string.c /home/utnso/workspace/commons/commons/collections/list.c
	gcc  -o nivel nivel.c cargador.c /home/utnso/workspace/commons/commons/config.c /home/utnso/workspace/commons/commons/collections/dictionary.c /home/utnso/workspace/commons/commons/string.c /home/utnso/workspace/commons/commons/collections/list.c -I/home/utnso/workspace/commons
	
