all: compile

compile:
	gcc -o prototipo prototipo.c -I/home/utnso/GITHUB/tp-2013-2c-the-grid/Commons-Library -L/home/utnso/GITHUB/tp-2013-2c-the-grid/Commons-Library/Debug -I/home/utnso/GITHUB/tp-2013-2c-the-grid/Biblioteca -L/home/utnso/GITHUB/tp-2013-2c-the-grid/Biblioteca/Debug -I/home/utnso/GITHUB/tp-2013-2c-the-grid/Biblioteca -L/home/utnso/GITHUB/tp-2013-2c-the-grid/Biblioteca/Debug -I/home/utnso/GITHUB/tp-2013-2c-the-grid/nivel-gui -L/home/utnso/GITHUB/tp-2013-2c-the-grid/nivel-gui/Debug -lnivel-gui -lCommons-Library -lBiblioteca -lncurses 
