all: compile

compile:
	gcc -o Debug/libnivel-gui.so nivel.c tad_items.c -I/home/utnso/GITHUB/tp-2013-2c-the-grid/Commons-Library -L/home/utnso/GITHUB/tp-2013-2c-the-grid/Commons-Library/Debug -lCommons-Library -lcurses -shared
