all: compile

compile:
	gcc -o Debug/libCommons\-Library.so commons/collections/dictionary.c commons/collections/list.c commons/collections/queue.c commons/bitarray.c commons/config.c commons/error.c commons/log.c commons/process.c commons/string.c commons/temporal.c commons/txt.c -shared

