all: compile

compile:
	gcc -o Debug/Personaje personaje.c -I/home/utnso/GITHUB/tp-2013-2c-the-grid/Commons-Library -L/home/utnso/GITHUB/tp-2013-2c-the-grid/Commons-Library/Debug -I/home/utnso/GITHUB/tp-2013-2c-the-grid/Biblioteca -L/home/utnso/GITHUB/tp-2013-2c-the-grid/Biblioteca/Debug -lCommons-Library -lBiblioteca -lpthread
